version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    command: sh entrypoint.sh
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8000:8008"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: